"""exercise db changed

Revision ID: 6af6ae6a8f48
Revises: 2b0041ab8110
Create Date: 2020-06-06 20:52:49.380551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af6ae6a8f48'
down_revision = '2b0041ab8110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('line_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'line_id')
    # ### end Alembic commands ###
